{% set version = "1.48.0" %}
{% set gomodule = "gitlab.com/gitlab-org/cli" %}

package:
  name: glab
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/-/archive/v{{ version }}/cli-v{{ version }}.tar.gz
  sha256: 45410de23a7bad37feeae18f47f3c0113d81133ad9bb97c8f0b8afc5409272c7

build:
  number: 0

requirements:
  build:
    - make      # [not win]
    - m2-make   # [win]
    - posix     # [win]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("go-cgo") }}
    - {{ stdlib("c") }}
    - go-licenses
  host: []
  run: []

test:
  commands:
    - glab --version
    # tries to write to home in windows
    - glab --help   # [unix]

about:
  home: https://{{ gomodule }}
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE
    - license-files/
  summary: A GitLab CLI tool bringing GitLab to your command line
  doc_url: https://docs.gitlab.com/ee/editor_extensions/gitlab_cli/
  description: |-
    GLab is an open source GitLab CLI tool bringing GitLab to your terminal next
    to where you are already working with git and your code without switching
    between windows and browser tabs. Work with issues, merge requests, watch
    running pipelines directly from your CLI among other features.

    glab is available for repositories hosted on GitLab.com and self-managed
    GitLab instances. glab supports multiple authenticated GitLab instances and
    automatically detects the authenticated hostname from the remotes available
    in the working Git directory.

extra:
  recipe-maintainers:
    - bollwyvl
