# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.53.0

package:
  name: glab
  version: ${{ version }}

source:
  url: https://gitlab.com/gitlab-org/cli/-/archive/v${{ version }}/cli-v${{ version }}.tar.gz
  sha256: 2930aa5dd76030cc6edcc33483bb49dd6a328eb531d0685733ca7be7b906e915
  target_directory: src/gitlab.com/gitlab-org/cli

build:
  number: 0
  script:
    file: build-glab

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("go-cgo") }}
    - go-licenses
    - make
    - if: target_goexe != ".exe"
      then:
        - ${{ stdlib("c") }}

tests:
  - script:
      - glab{{ target_goexe }} --version
      - glab{{ target_goexe }} --help

about:
  homepage: https://gitlab.com/gitlab-org/cli
  license: MIT
  license_file:
    - src/gitlab.com/gitlab-org/cli/LICENSE
    - license-files/
  summary: A GitLab CLI tool bringing GitLab to your command line
  description: |-
    GLab is an open source GitLab CLI tool bringing GitLab to your terminal next
    to where you are already working with git and your code without switching
    between windows and browser tabs. Work with issues, merge requests, watch
    running pipelines directly from your CLI among other features.

    glab is available for repositories hosted on GitLab.com and self-managed
    GitLab instances. glab supports multiple authenticated GitLab instances and
    automatically detects the authenticated hostname from the remotes available
    in the working Git directory.
  documentation: https://docs.gitlab.com/ee/editor_extensions/gitlab_cli

extra:
  recipe-maintainers:
    - bollwyvl
